cpp template package
pyros-dev/ros1_template pull request #10
Opened 2017-08-09 10:11 UTC by AlexReimann

Template package with pure cpp, no ros stuff

2017-08-14 05:20 UTC, asmodehn commented
I see... so catkin + pure C++,
Do you plan to add the ROSC++ in this package, as an the executable calling the lib for example ?

2017-08-16 01:54 UTC, AlexReimann commented
Yes, exactly. Splitting the library and the ROS part using it into two packages.

2017-08-22 03:15 UTC, asmodehn requested changes

2017-08-22 03:15 UTC, asmodehn commented on ros1_cpptemplate/CMakeLists.txt
> +catkin_package(
How about having the cpptemplate without catkin, using pure cmake stuff, to show pure c++ integration in ROS ?

2017-08-22 03:15 UTC, asmodehn commented on ros1_cpptemplate/README.rst
> +The only packge dependencies are on the *roslint* for checking the coding style (build dependency only) and *rosconsole* to have a uniform way for logging. In this package we are following http://wik
Can we use a non-ROS C++ linter ? maybe something embedded people are already familiar with?

2017-08-22 03:15 UTC, asmodehn commented on ros1_cpptemplate/README.rst
> +The only packge dependencies are on the *roslint* for checking the coding style (build dependency only) and *rosconsole* to have a uniform way for logging. In this package we are following http://wik
Same for rosconsole: Any way to do output in a way that we can pluginto rosconsole later ( like apache's log4cxx ) ?

2017-08-22 03:30 UTC, AlexReimann commented on ros1_cpptemplate/README.rst
> +The only packge dependencies are on the *roslint* for checking the coding style (build dependency only) and *rosconsole* to have a uniform way for logging. In this package we are following http://wik
What's the merit?
Sounds to me like ending up with two different systems.

2017-08-23 10:07 UTC, AlexReimann commented
Hol, some pip stuff failed?

2017-08-24 01:04 UTC, asmodehn commented
https://github.com/requests/requests/issues/3560

2017-08-24 01:11 UTC, asmodehn approved these changes

2017-08-24 01:14 UTC, asmodehn commented
After discussion, lets keep the ROS tools in the C++ template, since C++ doesn't have "official" set of tools, nor guarantee cross-platform, like most recent languages. The ROS tools (although not my personal first choice) are as valid as any other.

2017-08-24 01:30 UTC, merged